services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  app1:
    restart: on-failure
    build: ./app
    hostname: app1
    ports:
      - '81:5000'
  app2:
    restart: on-failure
    build: ./app
    hostname: app2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '8080:8080'
    depends_on:
    - app1
    - app2