version: '3'
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  portal1:
    restart: on-failure
    build: ./portal
    hostname: portal1
    ports:
      - '81:5000'
  portal2:
    restart: on-failure
    build: ./portal
    hostname: portal2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
      - '8080:8080'
    depends_on:
      - portal1
      - portal2
